<?php

/* BlakDownloader 3.7.5 - Tu7 [ Priv8 Edition ] */ 

$lang = array (
//main
'version'		=> 'BlakDownloader 3.7.5',
'homepage'	=> 'FrenchDebrid.eu',
'title'			=> ' > BlakDownloader 3.7.5',
'login'		=> '  ',
'password'		=> 'Password :',
'plugins'		=> 'Plugins',
'premium'		=> 'Premium Accounts :',
'moreacc'		=> '>>>',
'lessacc'		=> '<<<',
'main'		=> 'Main Window',
'donate'		=> 'Donate Acc',
'listfile'		=> 'Server Files',
'check'		=> 'Check Acc',
'log'			=> 'Log Out',
'welcome'		=> '  ',
'maxline'		=> '  ',
'example'		=> '  ',
'sbdown'		=> 'Download',
'dlhere'		=> 'Download here:',

// donate 
'donations'	=> '  ',
'acctype'		=> 'Account Type:',
'sbdonate'		=> 'Donate Account',
'invalid'		=> '<img src="images/error.png"> <font color=red><b>Invalid account. Please re-check your data!</b></font>',
'success'		=> '<font color=#FF3300>Thanks You , Account is Ok !</font>',
'dsuccess'		=> '<img src="images/success.png"><BR><b><font color=#86a5d5>Donate Success !</font></b>',
'getloading'		=> '<img src="images/loading.gif"><BR>checking...',
'notaccess'		=> 'You do not have permission to access this page !',

//check

//notice
'notice'		=> '<blink><font color=red>Auto del file after <B>%s</B>. Limit <B>%s</B> file per <B>%s</B> for <B>1</B> IP</font></blink><BR>',
'yourjobs'		=> 'Your IP: %s. Your jobs: %s (max: %s).You used %s (max: %s).<BR>',
'status'		=> 'File size limit: %s. Total jobs: %s (max: %s). Server load: %s (max allowed: %s). Users online: %s',

//time 

'ago'			=> 'ago',
'days'		=> 'days',
'hours'		=> 'hours',
'mins'		=> 'mins',
'sec'			=> 'sec',


//down
'errorget'		=> 'Failed to generate the link. Please try again !',
'errordl'		=> 'Your link has been generated by another ip address !',
'erroracc'		=> '<font color=red>Account/Cookie Error !!!</font>',
'svload'		=> 'Server load is too high.',
'issex'		=> '<B><font color=red>is this link sex ??? ==&#9658;</font> <a href=http://www.google.com/search?q=%s><font color=#00CC00>%s</font></a><br/><font color=#FFCC00>if not ==&#9658; Repost:</font> <font color=#0066CC>%s</font><font color=#FF3300>|</font><font color=#ff9999 face=Arial>not3x</font></b><BR>',
'errorlink'		=> '==&#9658; Invalid link !',
'manyjob'		=> 'Too many download jobs.',
'countMBIP'	=> '<center><b><i><font color=red>You only can download %s per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitPERIP'	=> '<center><b><i><font color=red>You only can download %s file per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitip'		=> 'Too many download jobs for this ip.',
'notsupport'	=> '<b><a href=%s style=\'TEXT-DECORATION: none\'><font color=red face=Arial size=2>%s</font></a>  <font color=#ffcc33 face=Arial size=2>==&#9658; Sorry. We do not support your link !</font></b><BR>',
'notdl'		=> '<b><a id=\'notsupport\' href=%s style=\'TEXT-DECORATION: none\'><font color=#ffcc33 face=Arial size=2>%s</font></a></b> <font color=red> ==&#9658; Can not get file size.</font><BR>',
'cantjob'		=> '<center><b><i><font color=red>Can not create new job</font></i></b></center>',
'filebig'		=> '<center><b><font color=#00CC00>%s</font> <font color=red>%s ==&#9658; File too big ! </font><font color=#3399FF>when allowed only</font> <font color=#FFCC00>%s</font></b></center>',

//Server Files
'notfound'		=> 'Not Found!',
'del'			=> 'Delete',
'rname'		=> 'Rename',
'notfile'		=> 'No Files Found',
'acdis'		=> 'Action Disabled',
'ac'			=> 'Action',
'name'		=> 'Name',
'size'			=> 'Size',
'date'		=> 'Date',
'original'		=> 'Original Link',
'clickcheck'	=> 'Click here to check link',
'total'		=> 'Total',
'used'		=> 'You used',
'reset'		=> 'Reset per',
'canl'			=> 'Cancel',
'deld'			=> 'Deleted!',
'nname'		=> 'New Name',
'bname'		=> 'You can\'t rename file to blank name!',
'rnameto'		=> 'renamed to',

//report
'dead'		=> '==&#9658; Link Dead !!!',
'again'		=> '==&#9658; please try again',
'notwork'		=> '==&#9658; Acc not work',
'unavailable'	=> 'Service Unavailable',
'disabletrial'	=> 'your link is temporary disable for trial account.',
'adult'		=> 'Adult Video Detected',
'ytb_captcha'	=> 'Captcha Found. Please run on different server',
'ytb_Error'		=> 'Error Locating Downlod URL',
'reportpass'	=> '<CENTER>The file you are trying to download is password protected. Please enter the password below.</CENTER>',
'outofbw'		=> '<font color=red>Account out of bandwidth !!!</font>',

);
?>